baseURL = "http://localhost:1313/"
theme = "salinger"
title = "salinger"
copyright = '2001 John Doe'
ignoreErrors = ["error-remote-getjson"]

[params]
DateFormat = "January 2006"

author = "John Doe"
description = "I'm a computer engineering student based in Modena, Italy. I like developing and designing random stuffs."
header = "<strong>Hi, I'm Alex. ðŸ‘‹ </strong>"
keywords = [ "Portfolio", "developer", "coding", "maker"]
showHeaderOnHomepage = false
#googleAnalytics = ""
twemoji = true
text404 = "Since the page you were looking for seems like doesn't exist, we <strong>strongly</strong> suggest you to better investigate the URL and/or go back to the <a href=\"/\">home</a>. </br></br> <iframe src=\"https://giphy.com/embed/aCKMaeduKfFXG\" width=\"480\" height=\"480\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen></iframe>"
#fontawesomekitcode = ""



[Menu]
[[Menu.Main]]
name = "Projects."
url = "/projects/"
weight = 1

[[Menu.Main]]
name = "Contact me."
url = "mailto:mail@mail.com"
weight = 2

[taxonomies]
	tag = "tags"
	category = "categories"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true